
version: '3'
services:

 
  workorder:
    build:
      dockerfile: Dockerfile
      context: ./workorder
    container_name: workorder
    ports:
      - "8001:8001"
    restart: always

    volumes:
      - .:/app
      - /app/workorder/node_modules

    env_file:
      - ./workorder/.env.dev
  vendor:
    build:
      dockerfile: Dockerfile
      context: ./vendor
    container_name: vendor
    ports:
      - "8002:8002"
    restart: always
    
    volumes:
      - .:/app
      - /app/vendor/node_modules
    env_file:
      - ./vendor/.env.dev
  user:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: user
    ports:
      - "8003:8003"
    restart: always
    volumes:
      - .:/app/
      - /app/user/node_modules
    env_file:
      - ./user/.env.dev
  inventory:
    build:
      dockerfile: Dockerfile
      context: ./inventory
    container_name: inventory
    ports:
      - "8004:8003"
      - "3004:3004"
    restart: always

    volumes:
      - .:/app
      - /app/inventory/node_modules

    env_file:
      - ./inventory/.env.dev
  inward:
    build:
      dockerfile: Dockerfile
      context: ./inward-inventory
    container_name: inward
    ports:
      - "8005:8001"
    restart: always

    volumes:
      - .:/app
      - /app/inward-inventory/node_modules

    env_file:
      - ./inward-inventory/.env.dev
  outward:
    build:
      dockerfile: Dockerfile
      context: ./outward-inventory
    container_name: outward
    ports:
      - "8006:8002"
    restart: always

    volumes:
      - .:/app
      - /app/outward-inventory/node_modules

    env_file:
      - ./outward-inventory/.env.dev
  proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - user
      - vendor
      - workorder
      - inventory
      - inward
      - outward
    ports:
      - "80:80"
