
version: '3'
services:
 
  workorder:
    build:
      dockerfile: Dockerfile
      context: ./workorder
    container_name: workorder
    ports:
      - "8001:8001"
    restart: always

    volumes:
      - .:/app
      - /app/workorder/node_modules

    env_file:
      - ./workorder/.env.dev
  vendor:
    build:
      dockerfile: Dockerfile
      context: ./vendor
    container_name: vendor
    ports:
      - "8002:8002"
    restart: always
    
    volumes:
      - .:/app
      - /app/vendor/node_modules
    env_file:
      - ./vendor/.env.dev
  user:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: user
    ports:
      - "8003:8003"
    restart: always
    volumes:
      - .:/app/
      - /app/user/node_modules
    env_file:
      - ./user/.env.dev
  proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - user
      - vendor
      - workorder
    ports:
      - 80:80
